In [1]:
import numpy as np

## Ques1. Create a 3x3x3 array with random values

In [2]:
x = np.random.random((3,3,3))
print('3x3x3 Array:\n')
print(x)

3x3x3 Array:

[[[0.13873499 0.42658562 0.0511758 ]
  [0.88772959 0.32349636 0.11557715]
  [0.49807528 0.63088056 0.6344032 ]]

 [[0.30444352 0.81008222 0.496957  ]
  [0.54117873 0.54053626 0.70858382]
  [0.63183144 0.64148541 0.92821639]]

 [[0.18581978 0.0354151  0.87035905]
  [0.7329661  0.49033035 0.57200525]
  [0.38306049 0.73001335 0.35242244]]]


## Ques2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
matrix = np.zeros((5,5))
matrix = np.diag(1+np.arange(4),k = -1)
print('Matrix with 1,2,3,4 just below Diagonal:\n\n', matrix)

Matrix with 1,2,3,4 just below Diagonal:

 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## Ques3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
x = np.zeros((8,8), dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print('Check Borad Pattern:\n')
print(x)

Check Borad Pattern:

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ques4.  Normalize a 5x5 random matrix

In [5]:
x= np.random.randn(5,5)
print("Original Array:\n")
print(x)

xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)

print("\nAfter normalization:\n")
print(x)

Original Array:

[[ 2.21408555 -0.70208625 -1.01890838  0.24277446 -0.24155605]
 [-0.75846881  1.5162996  -1.76249205  2.12544693 -1.24588299]
 [ 1.0364664   0.76830482  2.64473797  0.63736128  0.66140175]
 [ 0.29222566  0.59671996  0.84638273  0.4609744  -1.15714339]
 [ 1.53070309  1.63744812  0.05871345  0.20043374  0.17279394]]

After normalization:

[[0.90228501 0.24060596 0.16871905 0.45499475 0.34510021]
 [0.22781276 0.74395746 0.         0.88217292 0.11721854]
 [0.63508336 0.57423753 1.         0.54452645 0.54998123]
 [0.46621522 0.53530494 0.5919534  0.50450429 0.13735354]
 [0.74722561 0.77144604 0.41323132 0.44538764 0.43911618]]


## Ques5. How to find common values between two arrays?

In [6]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = [10, 30, 40]
print("Array1: ", array1)
print("Array2: ", array2)
print("Common values between two arrays:", np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays: [10 40]


## Ques6. How to get the dates of yesterday, today and tomorrow?

In [7]:
import datetime as dt

today = dt.date.today()
yesterday = today - dt.timedelta(days = 1)
tomorrow = today + dt.timedelta(days = 1) 

print('Yesterday: ',yesterday)
print('Today: ', today)
print('Tomorrow: ', tomorrow)

Yesterday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


## Ques7. Consider two random array A and B, check if they are equal

In [8]:
a = np.array([[1,23,5],[6,9,40]])
b =  np.array([[1,23,5],[6,9,40]])
print('Array1:\n', a)
print('Array2:\n', b)
print('\nResult is True if the Arrays are Equal \nResult is False if the Arrays are Not Equal ')
np.array_equal(a,b)

Array1:
 [[ 1 23  5]
 [ 6  9 40]]
Array2:
 [[ 1 23  5]
 [ 6  9 40]]

Result is True if the Arrays are Equal 
Result is False if the Arrays are Not Equal 


True

## Ques8. Create random vector of size 10 and replace the maximum value by 0

In [9]:
vector = np.array([1,45,867,90,48,94,100,166,867,110])
print('Vector: ', vector)
print('Length of Vector: ', len(vector))

vector_max = vector.max() 
print('Maximum value:', vector_max)
index= np.where(vector == vector_max)
vector[index] = 0

print('Replacing {} by 0: {}'.format(vector_max, vector))

Vector:  [  1  45 867  90  48  94 100 166 867 110]
Length of Vector:  10
Maximum value: 867
Replacing 867 by 0: [  1  45   0  90  48  94 100 166   0 110]


## Ques9.  How to print all the values of an array?

In [10]:
# 1-D Array :
print('For 1-D Array:')
x = np.array([12, 34, 67, 89])
for i in range(len(x)):
    print(f"The element at index {i} is: {x[i]}")

# 2-D Array: 
print('\nFor 2-D Array:')
y = np.array([[13,57,45],[34,76,88],[92,21,19],[98,67,0]])
for i in range(len(y)):
    print(f"The element at index {i} is: {y[i]}")

For 1-D Array:
The element at index 0 is: 12
The element at index 1 is: 34
The element at index 2 is: 67
The element at index 3 is: 89

For 2-D Array:
The element at index 0 is: [13 57 45]
The element at index 1 is: [34 76 88]
The element at index 2 is: [92 21 19]
The element at index 3 is: [98 67  0]


## Ques10. Subtract the mean of each row of a matrix

In [11]:
arr = np.array([[1, 100, 0, 0], [2, 110, 0, 0], [3, 120, 0, 0]])
print('Initial Array:\n', arr)
print('Mean of Each row: ',arr.mean(axis=1))
mean = arr - arr.mean(axis=1, keepdims=True) 
print('\nResultant Matrix After Subtracting Mean:\n',mean)

Initial Array:
 [[  1 100   0   0]
 [  2 110   0   0]
 [  3 120   0   0]]
Mean of Each row:  [25.25 28.   30.75]

Resultant Matrix After Subtracting Mean:
 [[-24.25  74.75 -25.25 -25.25]
 [-26.    82.   -28.   -28.  ]
 [-27.75  89.25 -30.75 -30.75]]


## Ques11.  .Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
Z = np.ones(10)
print("Initial Vector:\n",Z)
I = np.random.randint(0, len(Z),20)
print("Random Values:\n",I)
Z += np.bincount(I, minlength=len(Z))
print("Resultant Vector:\n",Z)

Initial Vector:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Random Values:
 [4 0 3 0 3 1 8 1 4 6 7 4 2 8 7 7 7 8 6 0]
Resultant Vector:
 [4. 3. 2. 3. 4. 1. 3. 5. 4. 1.]


## Ques12. How to get the diagonal of a dot product?

In [13]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

print("Array A:\n", A)
print("Array B:\n", B)

print('\nDot product:\n',np.dot(A,B))
dot = np.diag(np.dot(A, B))
print('\nThe Diagonal Elements are:\n', dot)

Array A:
 [[7 0 5]
 [4 1 9]
 [2 4 9]]
Array B:
 [[0 2 6]
 [0 4 2]
 [8 5 9]]

Dot product:
 [[ 40  39  87]
 [ 72  57 107]
 [ 72  65 101]]

The Diagonal Elements are:
 [ 40  57 101]


## Ques13. How to find the most frequent value in an array?

In [14]:
Z = np.random.randint(0,10,30)
print ("Array:", Z)
print('Most Frequent Value:', np.bincount(Z).argmax())

Array: [3 3 1 8 8 2 3 0 0 1 6 3 6 4 1 5 1 8 1 7 4 8 0 0 1 1 5 3 3 9]
Most Frequent Value: 1


## Ques14. How to get the n largest values of an array

In [15]:
Z = np.arange(100)
np.random.shuffle(Z)
n = int(input('Enter the value of n: '))
print(f"{n} Largest values in array: ", Z[np.argsort(Z)[-n:]])

Enter the value of n: 3
3 Largest values in array:  [97 98 99]


## Ques15. How to create a record array from a regular array?

In [16]:
print('For a Single Array:\n')
x3 = np.array([['Riya',98, 99],['Ankita', 90, 92],['Divyam', 89, 90]])

print('Regular Array:\n', x3)
rec = np.core.records.fromarrays(x3.T,names='name,mks1,mks2',formats='S80, i8, i8') # The arrays are now transposed'

print('\nRecord Array:', rec)
print('Type of Result:', type(rec))

For a Single Array:

Regular Array:
 [['Riya' '98' '99']
 ['Ankita' '90' '92']
 ['Divyam' '89' '90']]

Record Array: [(b'Riya', 98, 99) (b'Ankita', 90, 92) (b'Divyam', 89, 90)]
Type of Result: <class 'numpy.recarray'>


In [17]:
x1 = np.array([1,2,3,4])
x2 = np.array(['R','I','Y','A'])

print('Regular Array 1:',x1)
print('Regular Array 2:',x2)

records = np.core.records.fromarrays([x1,x2], names='Col1, Col2') # The arrays are now transposed 

print('\nRecord Array:', records)
print('Type of Result:', type(records))

Regular Array 1: [1 2 3 4]
Regular Array 2: ['R' 'I' 'Y' 'A']

Record Array: [(1, 'R') (2, 'I') (3, 'Y') (4, 'A')]
Type of Result: <class 'numpy.recarray'>
